title: Praise the Hack
description: "A blog for edgerunners."
author:
  name: "Lifestor"
  email: "lifestor@protonmail.com"
  url: "https://github.com/Lifestor/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Lifestor"
year : "2022"
